/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_imtne_ilog_Display */

#ifndef _Included_fr_imtne_ilog_Display
#define _Included_fr_imtne_ilog_Display
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_imtne_ilog_Display
 * Method:    displayLine
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_imtne_ilog_Display_displayLine
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
